// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_Claim(ZNetPeer,ZNetPeer,System.Int64)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_God(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_Ping(ZNetPeer,Player)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_SetBeard(ZNetPeer,System.String,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_SetHair(ZNetPeer,System.String,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_SetModel(ZNetPeer,System.Int32,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_Teleport(ZNetPeer,ZNetPeer,ZNetPeer,System.Single,System.Single,System.Single)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_Version(ZNetPeer,Player)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_Help(ZNetPeer,System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_AdminList(ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ClanAcceptInvite(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ClanInvite(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ClanKick(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ClanLeave(ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_PartyAcceptInvite(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_PartyInvite(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_PartyKick(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_PartyLeave(ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_AdminAdd(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_AdminRemove(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ClanChat(ZNetPeer,System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ClanCreate(ZNetPeer,System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_PartyChat(ZNetPeer,System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ServerBan(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ServerKick(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_SetName(ZNetPeer,System.String,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_ServerUnban(ZNetPeer,System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.DebugCommand_ServerFPS(ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.DebugCommand_SetActiveArea(ZNetPeer,System.Int32)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_NoCost(ZNetPeer,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.DebugCommand_SaveWorld(ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.DebugCommand_Stats(ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_GiveItem(ZNetPeer,System.String,System.Int32,ZNetPeer)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_GiveItemClient(ValheimMP.Framework.Events.OnChatMessageArgs,System.String,System.Int32,System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ValheimMP.ChatCommands.ChatCommands.Command_Teleport(ZNetPeer,ZNetPeer,ZNetPeer,System.Nullable{System.Single},System.Single,System.Single)")]
